name: Test Pipeline for opened PR
on:
  pull_request:
    branches: [ main, develop ] #put your branches which you want to execute test pipeline
    types: [opened, syncronize]

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.event.pull_request.number }}
      cancel-in-progress: true
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          yarn
          echo "$(git branch)"
      - name: Test Success
        run: yarn test

  execute_on_failure:
    runs-on: ubuntu-latest
    needs: [test]
    if: failure()
    steps:
      - name: Notify error
        run: echo 'test failed!'
