name: PR Test
on:
  pull_request:
    branches: [ main ] #put your branches which you want to execute test pipeline

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn
      - name: Test Success
        run: yarn test
      - name: Test Failed
        run: yarn error_test
      - name: Execute on failure
        if: always()
        run: |
        echo ${{ job.status }}
        echo ${{ job.status == 'failure' }}
      - name: Execute on failure
        if: ${{ (job.status == 'failure') }}
        run: echo 'test failed!'
