name: Test Pipeline for Merged PR
on:
  pull_request:
    branches: [ main, develop ]
    types: [ closed ]
concurrency: 
      group: ${{ github.event.pull_request.number }}
      cancel-in-progress: true
jobs:
  test_merged_pr:
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo ${{ github.base_ref }}
          echo ${{ github.head_ref }}
          echo ${{ github }}
      - name: Run test
        uses: ./
        id: test-pipeline
      - name: test
        run: |
          echo ${{ github.base_ref }}
          echo ${{ github.head_ref }}
          echo ${{ github }}
  publish:
    needs: test_merged_pr
    if: ${{ startsWith(github.head_ref, 'release/') && (github.base_ref == 'main') && (github.event.pull_request.merged == true) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: yarn
      - name: Publish package
        run: |
          yarn
          # yarn build
          yarn publish --access public
          echo "NEW_VERSION=$(npm pkg get version | tr -d '"')" >> $GITHUB_ENV
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
      - name: Push tag
        run: |
          git tag v${{ env.NEW_VERSION }}
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
