name: Publish Package to Npm
on:
  pull_request:
    branches: [ main ]
jobs:
  publish:
    # if:  startsWith(github.head_ref, 'release/')
    if:  startsWith(github.head_ref, 'feature')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish package
        run: |
          echo ${{ github.head_ref }}
          echo "TAG=$(echo ${{ github.head_ref }} | cut -b 9-)" >> $GITHUB_ENV
        # run: |
        #   yarn
        #   yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
      - name: Push tag
        run: |
          git tag $(echo ${{ github.head_ref }} | cut -b 9-)
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
