name: Send Error to Slack
on:
  workflow_run:
    workflows: [Publish Package to Npm, PR Test]
    types:
      - completed
jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: actions/checkout@v3
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump GitHub wf
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.workflow_run) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump GitHub pr number
        env:
          GITHUB_CONTEXT: ${{ github.event.workflow_run.pull_requests[0].number }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump GitHub event
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Get error log
        id: error_log
        run: |
          echo "ERROR_LOG<<EOF" >> $GITHUB_ENV
          echo "$(gh run view ${{ github.event.workflow_run.id }} --log-failed | tail -n 10)" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Notify error to slack
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "${{ github.event.workflow.name }} failed for <${{ github.server_url }}/${{ github.repository }}/pull/${{ env.PR_NUMBER }}|PR#${{ env.PR_NUMBER }}>",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":rotating_light:PIPELINE FAILED",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ github.event.workflow.name }} failed for <${{ github.server_url }}/${{ github.repository }}/pull/${{ env.PR_NUMBER }}|PR#${{ env.PR_NUMBER }}>"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Error log*\n$(gh run view ${{ github.event.workflow_run.id }} --log-failed | tail -n 10)\nCheck full logs in ${{ github.event.workflow_run.html_url }}"
                  }
                }
              ]
            }
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number }}
          SLACK_WEBHOOK_URL: ${{ secrets.TEST_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
